In [1]:
%matplotlib inline

import numpy as np
import scipy.linalg
import scipy.sparse.linalg
import matplotlib.pyplot as plt
import time
from numba import jit

In [2]:
@jit(nopython=True)
def build_pascal_orig(lc,nc):
    cnkc = np.zeros((lc,nc),dtype=np.int64)
    for i in range(1,lc+1):
        cnkc[i-1,0] = 1
    for i in range(1,lc+1):
        for j in range(2,nc+1):
            cnkc[i-1,j-1] = 0
    for in1 in range(2,lc+1):
        cnkc[in1-1,1] = np.sum(cnkc[in1-2,0:2])
        if nc-1 > 1:
            for in2 in range(1,nc+1):
                cnkc[in1-1,in2-1] = np.sum(cnkc[in1-2,0:in2])
    return cnkc, cnkc[lc-1,nc-1]

@jit(nopython=True)
def build_pascal(lc,nc):
    cnkc = np.zeros((lc,nc),dtype=np.int64)
    cnkc[0,0] = 1
    for in1 in range(2,lc+1):
        for in2 in range(1,nc+1):
            cnkc[in1-1,in2-1] = np.sum(cnkc[in1-2,0:in2])
#            print(cnkc)
    return cnkc, cnkc[lc-1,nc-1]

#@jit(nopython=True)
#def build_pascal_truncated_old(lc,nc,nmaxp,cnkc):
#    cnkct = np.zeros((lc,nc),dtype=np.int64)
#    cnkct[:,0:nmaxp] = cnkc[:,0:nmaxp]
##    cnkct = np.zeros((lc,nc),dtype=np.int64)
##    cnkct[0,0] = 1
##    for in1 in range(2,lc+1):
##        for in2 in range(1,nmaxp+1):
##            cnkct[in1-1,in2-1] = np.sum(cnkct[in1-2,0:in2])
#    for in1 in range(2,lc+1):
#        for in2 in range(nmaxp+1,nc+1):
#            cnkct[in1-1,in2-1] = np.sum(cnkct[in1-2,in2-nmaxp:in2])
##            print(cnkct)
#    return cnkct, cnkct[lc-1,nc-1]

@jit(nopython=True)
def build_pascal_truncated(lc,nc,nmaxp):
    cnkct = np.zeros((lc,nc),dtype=np.int64)
    cnkct[0,0] = 1
    for in1 in range(2,lc+1):
        for in2 in range(1,nmaxp+1):
            cnkct[in1-1,in2-1] = np.sum(cnkct[in1-2,0:in2])
    for in1 in range(2,lc+1):
        for in2 in range(nmaxp+1,nc+1):
            cnkct[in1-1,in2-1] = np.sum(cnkct[in1-2,in2-nmaxp:in2])
#            print(cnkct)
    return cnkct, cnkct[lc-1,nc-1]

In [3]:
Ns = 6 # number of sites
Na = 6 # number of atoms
nmax = 6 # |n> = |0>, |1>, ... |nmax> ((nmax+1) states)
lc = Ns + 1 # number of sites + 1
nc = Na + 1  # number of atoms + 1
nmaxp = nmax + 1 # nmax + 1

cnkc_orig, jmax_orig = build_pascal_orig(lc,nc)
print(cnkc_orig)
print(jmax_orig)

cnkc, jmax = build_pascal(lc,nc)
print(cnkc)
print(jmax)

#cnkct, jmaxt = build_pascal_truncated_old(lc,nc,nmaxp,cnkc)
#print(cnkct)
#print(jmaxt)

cnkct, jmaxt = build_pascal_truncated(lc,nc,nmaxp)
print(cnkct)
print(jmaxt)

[[  1   0   0   0   0   0   0]
 [  1   1   1   1   1   1   1]
 [  1   2   3   4   5   6   7]
 [  1   3   6  10  15  21  28]
 [  1   4  10  20  35  56  84]
 [  1   5  15  35  70 126 210]
 [  1   6  21  56 126 252 462]]
462
[[  1   0   0   0   0   0   0]
 [  1   1   1   1   1   1   1]
 [  1   2   3   4   5   6   7]
 [  1   3   6  10  15  21  28]
 [  1   4  10  20  35  56  84]
 [  1   5  15  35  70 126 210]
 [  1   6  21  56 126 252 462]]
462
[[  1   0   0   0   0   0   0]
 [  1   1   1   1   1   1   1]
 [  1   2   3   4   5   6   7]
 [  1   3   6  10  15  21  28]
 [  1   4  10  20  35  56  84]
 [  1   5  15  35  70 126 210]
 [  1   6  21  56 126 252 462]]
462
